import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import Footer from './shared/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="App">
          <Providers>{children}</Providers>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
